// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package scheduler.actions;

import java.util.List;
import scheduler.proxies.ApplicationSettings;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetApplicationSettings extends CustomJavaAction<IMendixObject>
{
	public GetApplicationSettings(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		IContext context = Core.createSystemContext();
		try {
			List<IMendixObject> result = Core.retrieveXPathQuery(context, "//" + ApplicationSettings.entityName);
			if( result.size() > 0 ) {
				return result.get(0);
			}
			
			context.startTransaction();			
			IMendixObject settings = Core.instantiate(context, ApplicationSettings.entityName);
			Core.commit(context, settings);
			context.endTransaction();
			
			return settings;
		}
		catch( Exception e ) {
			context.rollbackTransAction();
			throw e;
		}
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetApplicationSettings";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
