// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package scheduler.actions;

import java.util.ArrayList;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import scheduler.proxies.MicroflowName;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetMicroflowNames extends CustomJavaAction<java.util.List<IMendixObject>>
{
	public GetMicroflowNames(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE

		ArrayList<IMendixObject> mfList = new ArrayList<IMendixObject>();
		for( String mfName : Core.getMicroflowNames() ) {
			IMendixObject obj = Core.instantiate(getContext(), MicroflowName.entityName);
			obj.setValue(getContext(), MicroflowName.MemberNames.MicroflowName.toString(), mfName);
			
			mfList.add(obj);
		}
			
		
		return mfList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetMicroflowNames";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
