// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package scheduler.actions;

import java.util.List;
import scheduler.proxies.ApplicationSettings;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

public class ReleaseAdministrativeLock extends CustomJavaAction<Boolean>
{
	public ReleaseAdministrativeLock(IContext context)
	{
		super(context);
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = Core.createSystemContext();

		boolean locked = false;
		IMendixObject settings;
		List<IMendixObject> result = Core.retrieveXPathQuery(context, "//" + ApplicationSettings.entityName);
		if( result.size() > 0 ) {
			settings = result.get(0);
			locked = (Boolean) settings.getValue(context, ApplicationSettings.MemberNames.Locked.toString());
		}
		else 
			throw new CoreException("No settings found!");
		

		if( !locked )
			throw new CoreException("The settings weren't locked");
		
		try {
//			context.startTransaction();
			settings.setValue(context, ApplicationSettings.MemberNames.Locked.toString(), false);
			settings.setValue(context, ApplicationSettings.MemberNames.LockedBy.toString(), "");
			settings.setValue(context, ApplicationSettings.MemberNames.LockedOn.toString(), null);
			Core.commit(context, settings);
//			context.endTransaction();

			return true;
		}
		catch( Exception e ) {
//			context.rollbackTransAction();
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "ReleaseAdministrativeLock";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
